### ISSUE TITLE
error: open /usr/share/logstash/config/logstash.yml: read-only file system

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Cyb3rWard0g/HELK#156]
**Describe the problem**
When I use trial version of HELK, I get the following message before Logstash crashes:

```
[HELK-DOCKER-INSTALLATION-INFO] Running docker-entrypoint script..
2019/01/29 00:51:44 Setting 'xpack.monitoring.elasticsearch.username' from environment.
2019/01/29 00:51:44 Setting 'xpack.monitoring.elasticsearch.password' from environment.
2019/01/29 00:51:44 error: open /usr/share/logstash/config/logstash.yml: read-only file system
```
I tracked the problem back to this: https://github.com/elastic/logstash-docker/blob/master/build/logstash/bin/docker-entrypoint#L3

HELK mounts the main config via docker-compose volumes. Therefore, it runs to that issue.

**What steps did you take trying to fix the issue?**
In the docker-compose file of the trial versions, I updated the logstash sections to:

```
helk-logstash:
    build: helk-logstash/
    container_name: helk-logstash
    volumes:
      - ./helk-logstash/pipeline:/usr/share/logstash/pipeline
      - ./helk-logstash/output_templates:/usr/share/logstash/output_templates
      - ./helk-logstash/enrichments/cti:/usr/share/logstash/cti
      - ./helk-logstash/scripts/trial:/usr/share/logstash/scripts
    entrypoint: /usr/share/logstash/scripts/logstash-entrypoint.sh
    environment:
      - xpack.monitoring.elasticsearch.username=logstash_system
      - xpack.monitoring.elasticsearch.password=logstashpassword
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
    ports:
      - "5044:5044"
    restart: always
    depends_on:
      - helk-zookeeper
    networks:
      helk:
```
You can see that I am building Logstash from a dockerfile. This is build from the `helk-logstash/Dockerfile` available in the repo.

It looks now like this:

```
# HELK script: HELK Logstash Dockerfile
# HELK build Stage: Alpha
# Author: Roberto Rodriguez (@Cyb3rWard0g)
# License: GPL-3.0

# References: 
# https://cyberwardog.blogspot.com/2017/02/setting-up-pentesting-i-mean-threat_98.html

FROM docker.elastic.co/logstash/logstash:6.5.4
LABEL maintainer="Roberto Rodriguez @Cyb3rWard0g"
LABEL description="Dockerfile base for the HELK Logstash."

RUN mv /usr/share/logstash/config/logstash.yml /usr/share/logstash/config/logstash.yml.backup
COPY config/logstash.yml /usr/share/logstash/config/logstash.yml
```

**How could we replicate the issue?**
Run HELK with trial license option

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**

**What version of HELK are you using?**
Latest master 01/28/19

**What OS are you using to host the HELK?**
Linux - Ubuntu
**Any additional context?**
other log files, pictures, etc.
