### ISSUE TITLE
helk-elasticsearch container sucking up all memory

### ISSUE THREAD

**Issue by ssi0202** [Cyb3rWard0g/HELK#215]
did a fresh install of ubuntu 16.04 and a fresh pull from github

everything goes ok during the install but the helk-elasticsearch docker container takes all available system memory

i added the following to the helk-kibana-analysis-basic.yml file 

```
`helk-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: helk-elasticsearch
    secrets:
      - source: elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./helk-elasticsearch//scripts:/usr/share/elasticsearch/scripts
    entrypoint: /usr/share/elasticsearch/scripts/elasticsearch-entrypoint.sh
    environment:
      **- "ES_JAVA_OPTS=-Xms16g -Xmx16g"** <-- added this
      - cluster.name=helk-cluster
      - node.name=helk-1
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 20480
      nofile:
        soft: 160000
        hard: 160000
    restart: always
    networks:
      helk:
`
```
it works better now
also logstash is taking its sweet time installing plugins?

`100  2074  100    21  100  2053    214  20955 --:--:-- --:--:-- --:--:-- 21164
{"acknowledged":true}[HELK-LOGSTASH-DOCKER-INSTALLATION-INFO] Uploading logs-ipv6-dst.json template to elasticsearch..
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2066  100    21  100  2045    210  20482 --:--:-- --:--:-- --:--:-- 20656
{"acknowledged":true}[HELK-LOGSTASH-DOCKER-INSTALLATION-INFO] Uploading logs-ipv6-dst-nat.json template to elasticsearch..
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2082  100    21  100  2061    248  24426 --:--:-- --:--:-- --:--:-- 24535
{"acknowledged":true}[HELK-LOGSTASH-DOCKER-INSTALLATION-INFO] Uploading logs-ipv6-src.json template to elasticsearch..
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2066  100    21  100  2045    231  22542 --:--:-- --:--:-- --:--:-- 22722
{"acknowledged":true}[HELK-LOGSTASH-DOCKER-INSTALLATION-INFO] Uploading logs-ipv6-src-nat.json template to elasticsearch..
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2082  100    21  100  2061    343  33664 --:--:-- --:--:-- --:--:-- 34350
{"acknowledged":true}[HELK-LOGSTASH-DOCKER-INSTALLATION-INFO] Uploading logs-any-fields.json template to elasticsearch..
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   473  100    21  100   452    304   6563 --:--:-- --:--:-- --:--:--  6647
{"acknowledged":true}[HELK-LOGSTASH-DOCKER-INSTALLATION-INFO] Checking Logstash plugins..
ERROR: No plugins found
[HELK-LOGSTASH-DOCKER-INSTALLATION-INFO] Trying to install Logstash plugins over the Internet..
Validating logstash-filter-translate
Installing logstash-filter-translate
Installation successful
Validating logstash-filter-dns
Installing logstash-filter-dns
Installation successful
Validating logstash-filter-cidr
Installing logstash-filter-cidr
Installation successful
Validating logstash-filter-geoip
Installing logstash-filter-geoip
Installation successful
Updating logstash-filter-dissect
No plugin updated
Validating logstash-output-kafka
Installing logstash-output-kafka
Installation successful
Validating logstash-input-kafka
Installing logstash-input-kafka
Installation successful
Validating logstash-filter-alter
Installing logstash-filter-alter
Installation successful
Validating logstash-filter-fingerprint
Installing logstash-filter-fingerprint
Installation successful
Validating logstash-filter-prune
Installing logstash-filter-prune
Installation successful
Validating logstash-codec-gzip_lines
Installing logstash-codec-gzip_lines
Installation successful
Validating logstash-codec-netflow
Installing logstash-codec-netflow
Installation successful
Validating logstash-filter-i18n
Installing logstash-filter-i18n
Installation successful
Validating logstash-filter-environment
Installing logstash-filter-environment
Installation successful
Validating logstash-filter-de_dot
Installing logstash-filter-de_dot
Installation successful
Validating logstash-input-wmi
Installing logstash-input-wmi
Installation successful
Validating logstash-filter-clone
Installing logstash-filter-clone

`
