### ISSUE TITLE
Zeek / Corelight Import - Fails to Use geo

### ISSUE THREAD

**Issue by torrycrass** [Cyb3rWard0g/HELK#341]
**Describe the problem**
When importing Bro/Zeek/Corelight logs geo / geo_point is not being populated.

Filebeat with Zeek module enabled > Logstash > Elasticsearch parses the log and loads it but it does not contain geo location data.

I *believe* the problem is because of a renaming or processing failure per the filebeat log here:

```
2019-09-18T18:58:50.181-0700    DEBUG   [processors]    processing/processors.go:108    Fail to apply processor client{drop_fields=json.actions, rename=[{From:json To:zeek.notice} {From:zeek.notice.src To:source.address} {From:zeek.notice.dst To:destination.address} {From:zeek.notice.uid To:zeek.session_id} {From:zeek.notice.p To:destination.port} {From:zeek.notice.conn To:zeek.notice.connnection_id} {From:zeek.notice.iconn To:zeek.notice.icmp_id} {From:zeek.notice.id.orig_h To:source.address} {From:zeek.notice.id.orig_p To:source.port} {From:zeek.notice.id.resp_h To:destination.address} {From:zeek.notice.id.resp_p To:destination.port} {From:zeek.notice.proto To:network.transport} {From:zeek.notice.id.orig_p To:source.port} {From:zeek.notice.f.id To:zeek.notice.file.id} {From:zeek.notice.f.parent_id To:dzeek.notice.file.parent_id} {From:zeek.notice.f.source To:zeek.notice.file.source} {From:zeek.notice.f.is_orig To:zeek.notice.file.is_orig} {From:zeek.notice.f.seen_bytes To:zeek.notice.file.seen_bytes} {From:zeek.notice.f.total_bytes To:zeek.notice.file.total_bytes} {From:zzeek.notice.file_mime_type To:zeek.notice.file.mime_type}], drop_fields=zeek.notice.remote_location, zeek.notice.f, community_id=[target=network.community_id, fields=[source_ip=source.address, source_port=source.port, destination_ip=destination.address, destination_port=destination.port, transport_protocol=network.transport, icmp_type=icmp.type, icmp_code=icmp.code], seed=0]}: key not found
2019-09-18T18:58:50.181-0700    DEBUG   [rename]        actions/rename.go:81    Failed to rename fields in processor: target field source.port already exists, drop or rename this field first
2019-09-18T18:58:50.181-0700    DEBUG   [processors]    processing/processors.go:108    Fail to apply processor client{drop_fields=json.actions, rename=[{From:json To:zeek.notice} {From:zeek.notice.src To:source.address} {From:zeek.notice.dst To:destination.address} {From:zeek.notice.uid To:zeek.session_id} {From:zeek.notice.p To:destination.port} {From:zeek.notice.conn To:zeek.notice.connnection_id} {From:zeek.notice.iconn To:zeek.notice.icmp_id} {From:zeek.notice.id.orig_h To:source.address} {From:zeek.notice.id.orig_p To:source.port} {From:zeek.notice.id.resp_h To:destination.address} {From:zeek.notice.id.resp_p To:destination.port} {From:zeek.notice.proto To:network.transport} {From:zeek.notice.id.orig_p To:source.port} {From:zeek.notice.f.id To:zeek.notice.file.id} {From:zeek.notice.f.parent_id To:dzeek.notice.file.parent_id} {From:zeek.notice.f.source To:zeek.notice.file.source} {From:zeek.notice.f.is_orig To:zeek.notice.file.is_orig} {From:zeek.notice.f.seen_bytes To:zeek.notice.file.seen_bytes} {From:zeek.notice.f.total_bytes To:zeek.notice.file.total_bytes} {From:zzeek.notice.file_mime_type To:zeek.notice.file.mime_type}], drop_fields=zeek.notice.remote_location, zeek.notice.f, community_id=[target=network.community_id, fields=[source_ip=source.address, source_port=source.port, destination_ip=destination.address, destination_port=destination.port, transport_protocol=network.transport, icmp_type=icmp.type, icmp_code=icmp.code], seed=0]}: key not found, key not found
```
After this, the log file indicates that the record is loaded to the HELK instance and I am able to view the data in the dashboard but there are no fields for geo.

The files I've looked at to validate things are in place are:

/usr/share/filebeat/module/zeek/connection/manifest.yml:
```
ingest_pipeline: ingest/pipeline.json
input: config/connection.yml

requires.processors:
- name: geoip
  plugin: ingest-geoip
~
```

/usr/share/filebeat/module/zeek/connection/config/connection.yml
```
processors:
  - drop_fields:
      fields: ["json.orig_bytes","json.resp_bytes","json.tunnel_parents"]
  - rename:
      fields:
        - from: "json"
          to: "zeek.connection"

        - from: "zeek.connection.duration"
          to: "temp.duration"

        - from: "zeek.connection.id.orig_h"
          to: "source.address"

        - from: "zeek.connection.id.orig_p"
          to: "source.port"

        - from: "zeek.connection.id.resp_h"
          to: "destination.address"

        - from: "zeek.connection.id.resp_p"
          to: "destination.port"
```

/usr/share/filebeat/module/zeek/connection/ingest/pipeline.json
```
    {
      "set": {
        "field": "source.ip",
        "value": "{{source.address}}"
      }
    },
    {
      "set": {
        "field": "destination.ip",
        "value": "{{destination.address}}"
      }
    },
    {
      "script": {
        "lang": "painless",
        "source": "if (ctx.zeek.connection.local_orig == true && ctx.zeek.connection.local_resp == true) {ctx.network.direction = \"internal\"} else if (ctx.zeek.connection.local_orig == true && ctx.zeek.connection.local_resp == false) {ctx.network.direction = \"outbound\"} else if (ctx.zeek.connection.local_orig == false && ctx.zeek.connection.local_resp == true) {ctx.network.direction = \"inbound\"} else {ctx.network.direction = \"external\"}"
      }
    },
    {
      "geoip": {
        "field": "destination.ip",
        "target_field": "destination.geo"
      }
    },
    {
      "geoip": {
        "field": "source.ip",
        "target_field": "source.geo"
      }
    }
```

Sanitized Sample Data:
```
{"_path":"conn","_system_name":"sensor","_write_ts":"2019-07-02T15:53:03.511364Z","ts":"2019-07-02T15:52:46.377889Z","uid":"CByC0qkmPzrL8w4Akj","id.orig_h":"12.34.56.78","id.orig_p":64069,"id.resp_h":"98.76.54.32","id.resp_p":135,"proto":"tcp","service":"dce_rpc","duration":12.133461,"orig_bytes":2355,"resp_bytes":395,"conn_state":"SF","local_orig":false,"local_resp":true,"missed_bytes":0,"history":"ShADadFf","orig_pkts":9,"orig_ip_bytes":2727,"resp_pkts":7,"resp_ip_bytes":687,"tunnel_parents":[],"orig_l2_addr":"00:11:22:33:44:55","resp_l2_addr":"aa:bb:cc:dd:ee:ff"}
```

**What steps did you take trying to fix the issue?**
I've attempted to modify the fields, such as change `desination.address` to `destination.ip` and so on. That didn't work (I didn't think it would but I'm pretty stuck on this).

I've attempted to search for the error on Google but so far have not been able to locate a solution or even an explanation of the problem.

I posted into the #logstash IRC channel but have so far had no response.

I've posted to the Beats, Filebeat forum so far also with no response (https://discuss.elastic.co/t/zeek-import-timestamp-geo-failing/198536)

The above issue includes a timestamp problem which I worked around by changing from going filebeat > elasticsearch to filebeat > logstash which processed the `ts` field properly.

I'm honestly not sure what to do as I'm still extremely new to the Elastic platform in general and the error messages really don't give me context that I understand enough to know where to look for the problem.

**How could we replicate the issue?**
Attempt to load a Zeek/Bro/Corelight log entry via Filebeat sending to Logstash. Turn on debug for more detailed information.

**What version of HELK are you using?**
Latest per installation script.

**What OS are you using to host the HELK?**
Ubuntu 16.04 LTS

**Any additional context?**
other log files, pictures, etc.
Any help on this will be greatly appreciated, and if I can get some understanding out of how this is set up and what I'm doing wrong, I'm more than willing to put together contribution to the project to simplify (or even just explain) what is going on here so others can get a better understanding of what is going on (and hopefully avoid my same problems).

**Comment by torrycrass** [comment]
Is there some type of data flow mapping available that explains which files and fields are responsible for getting the data from point A to point B? Perhaps that will help me identify exactly where the breakdown is occurring and in which tool.

**Comment by neu5ron** [comment]
hey, great question and troubleshooting!
I wouldnt use the geo processor. We map that in the HELK pipeline. 

if you change destination ip to to dst_ip_addr and destination port to dst_port
source.address to src_ip_addr and source.port to src_port
the protocol/proto should be mapped to network_protocol
this will then give you the community ID and can pivot on IPs and ports as a short term fix.


so going beats to logstash is the way to go.

upcoming release ( less than 2 weeks) will be able to support to Kafka as well the logstash route. I dont want to do too many temporary work arounds because of the pending release, hope that makes sense.

feel free to ask anything else, im willing to help before the release as much as I can

**Comment by torrycrass** [comment]
Thank you for the reply and encouragement. Overall, trying... still daunting for sure.

The goal was to get geo location data into the data set.

I'm just double checking this but based on your reply, am I correct in concluding that *current* support for geo location in the zeek filebeat module with HELK is not possible?

Or is it that the changes you suggested will "fix" that by something akin to bypassing what filebeat is trying to do with the data?

Sorry if these are basic questions or assumptions, I'm still trying to wrap my head around most of what's going on here.

**Comment by neu5ron** [comment]
no problem on the question, happy to help especially since your also doing
your own troubleshooting/learning 👍
so yes, the changes I recommended will add the geo data.
To give more context, in order to get the best usage out of HELK and in
order to make things work in a supported fashion for HELK - its best to
make those changes. Filebeat module for Zeek adds some of its own
modifications - which your conclusion is correct.

I hope that helps, feel free continue the discussion.

**Comment by torrycrass** [comment]
And thank you for the help, I can't tell you how much I appreciate it, especially with as close to working as I have it for what's needed currently the last bit (I think) is this geo location data.

Hrm, I've tried to update fields but I get the feeling I'm missing something since the updates didn't seem to have any effect. I'm stepping back for just a sec and providing the setup and config files below (that I have updated).

1. I have loaded filebeat onto the host system that HELK is installed on.
2. I have updated the filebeat configuration files (as shown below).
3. I am still receiving the same error as I originally posted above (not reposting here since it's there).

Do I have these edits right or am I looking in the wrong spot, maybe my edits here are wrong?


FILE: /usr/share/filebeat/module/zeek/connection/manifest.yml
```
module_version: 1.0

var:
  - name: paths
    default:
      - /var/log/bro/current/conn.log
    os.linux:
      - /var/log/bro/current/conn.log
    os.darwin:
      - /usr/local/var/logs/current/conn.log
  - name: tags
    default: [zeek.connection]
  - name: community_id
    default: true

ingest_pipeline: ingest/pipeline.json
input: config/connection.yml

requires.processors:
- name: geoip
  plugin: ingest-geoip
```

FILE: /usr/share/filebeat/module/zeek/connection/config/connection.yml
```
type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$"]
tags: {{.tags}}

json.keys_under_root: false

processors:
#  - drop_fields:
#      fields: ["json.orig_bytes","json.resp_bytes","json.tunnel_parents","source.port"]
  - rename:
      fields:
        - from: "json"
          to: "zeek.connection"

#        - from: "zeek.connection.duration"
#          to: "temp.duration"

        - from: "zeek.connection.id.orig_h"
          to: "src_ip_addr"

        - from: "zeek.connection.id.orig_p"
          to: "src_port"

        - from: "zeek.connection.id.resp_h"
          to: "dst_ip_addr"

        - from: "zeek.connection.id.resp_p"
          to: "dst_port"

#        - from: "zeek.connection.proto"
#          to: "network.transport"

#        - from: "zeek.connection.service"
#          to: "network.application"

#        - from: "zeek.connection.uid"
#          to: "zeek.session_id"

#        - from: "zeek.connection.orig_ip_bytes"
#          to: "source.bytes"

#        - from: "zeek.connection.resp_ip_bytes"
#          to: "destination.bytes"

#        - from: "zeek.connection.orig_pkts"
#          to: "source.packets"

#        - from: "zeek.connection.resp_pkts"
#          to: "destination.packets"

#        - from: "zeek.connection.conn_state"
#          to: "zeek.connection.state"

      ignore_missing: false
      fail_on_error: true
{{ if .community_id }}
  - if:
      equals.network.transport: icmp
    then:
      community_id:
        fields:
          source_ip: src_ip_addr
          destination_ip: dst_ip_addr
          icmp_type: src_port
          icmp_code: dst_port
    else:
      community_id:
        fields:
          source_ip: src_ip_addr
          destination_ip: src_ip_addr
{{ end }}

```

FILE: /usr/share/filebeat/module/zeek/connection/ingest/pipeline.json
```
{
  "description": "Pipeline for normalizing Zeek conn.log",
  "processors": [
    {
      "script": {
        "lang": "painless",
        "source": "ctx.event.created = ctx['@timestamp']; ctx['@timestamp'] = (long)ctx['zeek']['connection']['ts'] * 1000; ctx.zeek.connection.remove('ts');"
      }
    },
    {
      "script": {
        "lang": "painless",
        "source": "ctx.event.duration = Math.round(ctx.temp.duration * params.scale)",
        "params": {
          "scale": 1000000000
        },
        "if": "ctx.temp?.duration != null"
      }
    },
    {
      "remove": {
        "field": "temp.duration",
        "ignore_missing": true
      }
    },
    {
      "set": {
        "field": "event.id",
        "value": "{{zeek.session_id}}",
        "if": "ctx.zeek.session_id != null"
      }
    },
    {
      "script": {
        "lang": "painless",
        "source": "if (ctx.zeek.connection.local_orig) ctx.tags.add(\"local_orig\");",
        "if": "ctx.zeek.connection.local_orig != null"
      }
    },
    {
      "script": {
        "lang": "painless",
        "source": "if (ctx.zeek.connection.local_resp) ctx.tags.add(\"local_resp\");",
        "if": "ctx.zeek.connection.local_resp != null"
      }
    },
    {
      "set": {
        "field": "source.ip",
        "value": "{{src_ip_addr}}"
      }
    },
    {
      "set": {
        "field": "destination.ip",
        "value": "{{dst_ip_addr}}"
      }
    },
    {
      "script": {
        "lang": "painless",
        "source": "if (ctx.zeek.connection.local_orig == true && ctx.zeek.connection.local_resp == true) {ctx.network.direction = \"internal\"} else if (ctx.zeek.connection.local_orig == true && ctx.zeek.connection.local_resp == false) {ctx.network.direction = \"outbound\"} else if (ctx.zeek.connection.local_orig == false && ctx.zeek.connection.local_resp == true) {ctx.network.direction = \"inbound\"} else {ctx.network.direction = \"external\"}"
      }
    },
    {
      "geoip": {
        "field": "destination.ip",
        "target_field": "destination.geo"
      }
    },
    {
      "geoip": {
        "field": "source.ip",
        "target_field": "source.geo"
      }
    }
  ],
  "on_failure" : [{
    "set" : {
      "field" : "error.message",
      "value" : "{{ _ingest.on_failure_message }}"
    }
  }]
}
```

**Comment by neu5ron** [comment]
just to confirm - output is to logstash correct?

**Comment by torrycrass** [comment]
Yes.

Per excerpt from `filebeat.yml` config file:
```
#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["172.18.0.8:5044"]
```

and full config of `/etc/filebeat/modules.d/zeek.yml`
```
# Module: zeek
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.3/filebeat-module-zeek.html

- module: zeek
  # All logs
  connection:
    enabled: true
  dns:
    enabled: true
  http:
    enabled: true
  files:
    enabled: true
  ssl:
    enabled: true
  notice:
    enabled: true

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths: ["/opt/log_import/zeek/*"]
```
