### ISSUE TITLE
Elastalert query filter not working - but query works fine in Kibana

### ISSUE THREAD

**Issue by SecOpsWarrior** [Cyb3rWard0g/HELK#422]
For the sigma_av_relevant_files.yml rule, I have added some regex to ignore certain powershell files generated whenever a script is kicked off by our RMM. The query works PERFECTLY in Kibana when I test it, but does not do the same filtering job in Elastalert, and I get flooded with the alerts that should be filtered out.

Any ideas why this works great in ES but not in Elastalert?

ES QUERY:
'''
GET _search
{
  "query": {
    "query_string": {
      "query": "(file_name.keyword:(C\\:\\Windows\\Temp\\* OR C\\:\\Temp\\*OR *\\Client\\* OR C\\:\\PerfLogs\\* OR *\\Users\\Public\\* OR C\\:\\Users\\Default\\* OR *.ps1 OR *.vbs OR *.bat OR *.chm OR *.xml OR *.txt OR *.jsp OR *.jspx OR *.asp OR *.aspx OR *.php OR *.war) NOT file_name.keyword:(/.*windows.temp.[a-z0-9_]+\\.[a-z0-9]{3}\\.ps1/ OR /.*users[a-z0-9\\]+temp.[a-z0-9]+\\.[a-z0-9]{3}\\.ps1/))"
    } 
  }
}
'''
Elastalert rule (doesn't filter the NOT at all and alerts come pouring in)
'''
alert:
- debug

description: Detects an Antivirus alert in a highly relevant file path or with a relevant file name

filter:
- query:
    query_string:
      query: (file_name.keyword:(C\\:\\Windows\\Temp\\* OR C\\:\\Temp\\*OR *\\Client\\* OR C\\:\\PerfLogs\\* OR *\\Users\\Public\\* OR C\\:\\Users\\Default\\* OR *.ps1 OR *.vbs OR *.bat OR *.chm OR *.xml OR *.txt OR *.jsp OR *.jspx OR *.asp OR *.aspx OR *.php OR *.war) NOT file_name.keyword:(/.*windows.temp.[a-z0-9_]+\\.[a-z0-9]{3}\\.ps1/ OR /.*users[a-z0-9\\]+temp.[a-z0-9]+\\.[a-z0-9]{3}\\.ps1/))

index: logs-*
name: Antivirus-Relevant-File-Paths-Alerts_0
priority: 2
realert:
  minutes: 0
type: any
'''
EXAMPLE file_name that should be filtered, but still throws an alert:
'''
"file_name" : """c:\windows\temp\5ttwu3tm.enp.ps1""",
'''
#### What version of HELK are you using

just provide the date you cloned the HELK repo:
```
1/25/2020
```

**Comment by SecOpsWarrior** [comment]
Figured it out. For some reason, using parens to enclose the query in elastalert wasnt properly sending the whole query, it was only grabbing he first condition.  Changing the elastalert query to the below resolved the issue. Does anyone have an idea why this is? Bug or expected behavior?

```
filter:
- query:
    query_string:
      query: "file_name.keyword:(C\\:\\Windows\\Temp\\* OR C\\:\\Temp\\*OR *\\Client\\* OR C\\:\\PerfLogs\\* OR *\\Users\\Public\\* OR C\\:\\Users\\Default\\* OR *.ps1 OR *.vbs OR *.bat OR *.chm OR *.xml OR *.txt OR *.jsp OR *.jspx OR *.asp OR *.aspx OR *.php OR *.war) NOT file_name.keyword:(/.*windows.temp.[a-z0-9_]+\\.[a-z0-9]{3}\\.ps1/ OR /.*users[a-z0-9\\]+temp.[a-z0-9]+\\.[a-z0-9]{3}\\.ps1/)"
```
