### ISSUE TITLE
problem connection client windows winlogbeat to server ubuntu HELK

### ISSUE THREAD

**Issue by nugnugrawk** [Cyb3rWard0g/HELK#481]
![winlogissue](https://user-images.githubusercontent.com/19874624/87015590-d140f700-c1f7-11ea-97b8-22c93c5e201a.png)

how to fix this problem ? 

I have configuration kibana server and winlogbeat with https://github.com/Cyb3rWard0g/HELK/blob/master/configs/winlogbeat/winlogbeat.yml configuration

**Comment by nugnugrawk** [comment]
![logs1](https://user-images.githubusercontent.com/19874624/87035281-4c63d680-c213-11ea-9b37-5b8cef8ea439.png)
![logs2](https://user-images.githubusercontent.com/19874624/87035292-51c12100-c213-11ea-8e0c-ed07be725018.png)
this is file winlogbeat.yml in client (windows)

**Comment by Cyb3rWard0g** [comment]
Do you have HELK installed on your WIndows System? It is pointing to 127.0.0.1. You have to give it the IP of your HELK server. The recommended setup for HELK is a simple Ubuntu Server in the network. Also, Elasticsearch is not exposed directly. All traffic goes to either Kafka or Logstash. You will need a config like this one:

```
winlogbeat.event_logs:
  - name: Application
    ignore_older: 30m
  - name: Security
    ignore_older: 30m
  - name: System
    ignore_older: 30m
  - name: Microsoft-windows-sysmon/operational
    ignore_older: 30m
  - name: Microsoft-windows-PowerShell/Operational
    ignore_older: 30m
    event_id: 4103, 4104
  - name: Windows PowerShell
    event_id: 400,600
    ignore_older: 30m
  - name: Microsoft-Windows-WMI-Activity/Operational
    event_id: 5857,5858,5859,5860,5861

#----------------------------- Kafka output --------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  # Place your HELK IP(s) here (keep the port).
  # If you only have one Kafka instance (default for HELK) then remove the 2nd IP that has port 9093
  hosts: ["<HELK-IP>:9092]
  topic: "winlogbeat"
  ############################# HELK Optimizing Latency ######################
  max_retries: 2
  max_message_bytes: 1000000
```

That should be on your client/Windows box with WInlogbeat running.
