### ISSUE TITLE
Deal with non-english endpoints OS

### ISSUE THREAD

**Issue by ericbsdr** [Cyb3rWard0g/HELK#86]
**Describe the problem**
My endpoints are French Windows OS. Winlogeat send some french words to logtash.
For example when hunting Powershell activities : the work **value is "valeur"** and **name is "nom"**
So logstash is unable to deal with the message received.

**What steps did you take trying to fix the issue?**
I modified `/etc/logstash/conf.d/10-powershell-filter.conf` line 48 with

`

43    kv {
44         source => "PayloadParams"
45         value_split => "="
46         allow_duplicate_values => false
47         target => "[powershell][param]"
48         include_keys => [ "nom", "valeur" ]
49   }

 `

**Am I doing this the right way ?**

**How could we replicate the issue?**
Use a non-english Windows 2012R2 server. French for example.

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**
No issue during install.

**What version of HELK are you using?**
HELK build version: 0.9 (BETA)
HELK ELK version: 6.x

**What OS are you using to host the HELK?**
`cat /etc/issue`
Debian GNU/Linux 9
`uname -ar`
Linux helk 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux

**Any additional context?**
Here is an output received. You will see **{"nom"=>"« TypeName »", "valeur"=>"« net.webclient »"}**

 `output received {"event"=>{"computer_name"=>"srv.domain.lan", "user"=>{"type"=>"User", "domain"=>"DOMAIN", "name"=>"da_eric", "identifier"=>"S-1-5-21-1618238945-667502674-313073013-9569"}, "host"=>{"name"=>"srv"}, "event_id"=>4103, "task"=>"Exécution du pipeline", "opcode"=>"À utiliser lorsque l'opération exécute uniquement une méthode", "provider_guid"=>"{A0C1853B-5C40-4C15-8766-3CF1C58F985A}", "thread_id"=>66040, "level"=>"Information", "tags"=>["beats_input_codec_plain_applied"], "record_number"=>"57538", "log_name"=>"Microsoft-Windows-PowerShell/Operational", "@version"=>"1", "source_name"=>"Microsoft-Windows-PowerShell", "beat"=>{"version"=>"6.3.1", "name"=>"srv", "hostname"=>"srv"}, "process_id"=>65052, "version"=>1, "activity_id"=>"{F7D559C7-182A-0001-42A3-DEF72A18D401}", "type"=>"wineventlog", "powershell"=>{"param"=>{"nom"=>"« TypeName »", "valeur"=>"« net.webclient »"}}, "event_data"=>{}, "@timestamp"=>2018-07-11T11:42:06.437Z}}`

Thanks for any help :-)

**Comment by Cyb3rWard0g** [comment]
Thank you for the details @ericbsdr ! I am not sure how to add the flexibility to have the pipeline dynamic enough for different languages. did your update to the logstash config work?? I see you edited the powershell config. let me know.

**Comment by ericbsdr** [comment]
Hi. Yes I updated the `/etc/logstash/conf.d/10-powershell-filter.conf`file because powershell log seems to be more frenchy than others :-) I don't know why. Will my configuration be overwritten if I install next HELK updates ?

**Comment by Cyb3rWard0g** [comment]
got it! @ericbsdr as long as you make a copy of your pipeline folder and then make sure it is the main one to be mounted in the Logstash container, you should be fine.

**Comment by Cyb3rWard0g** [comment]
@ericbsdr your logstash pipeline will not be overwritten since the logstash service mounts the local logstash pipeline configs as shown in the docker compose config:
```
helk-logstash:
    image: docker.elastic.co/logstash/logstash:6.3.2
    container_name: helk-logstash
    volumes:
      - ./helk-logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./helk-logstash/pipeline:/usr/share/logstash/pipeline
      - ./helk-logstash/output_templates:/usr/share/logstash/output_templates
      - ./helk-logstash/enrichments/cti:/usr/share/logstash/cti
    environment:
      - "LS_JAVA_OPTS=-Xms2g -Xmx2g"
    restart: always
    depends_on:
      - helk-elasticsearch
    networks:
      helk:
        aliases:
          - helk_logstash.hunt.local
```
Closing this issue since there is nothing to fix here. Feel free to re-open the issue or opening a new one if you have any other issues. Thank you @ericbsdr 👍
