### ISSUE TITLE
add nodes to helk-elk

### ISSUE THREAD

**Issue by ssi0202** [Cyb3rWard0g/HELK#89]
is there a goto way to add more nodes to the helk-elk container or is the correct docker way to add more helk-elk containers ie more seperate containers in the docker compose file

im looking to powerup a elasticsearch cluster and not just a single node

**Comment by Cyb3rWard0g** [comment]
Hey @ssi0202 ! that is on the roadmap, but in the mean time I believe you can do the same thing as explained by elastic: 
```
version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
```
Let me know if that helps https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html. I believe you will have to update the logstash output too. I havent done that yet.
